# Generated by Django 3.2.5 on 2021-07-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('store', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=255)),
                ('grade', models.CharField(max_length=1)),
                ('image', models.CharField(max_length=255)),
                ('salt', models.FloatField(null=True)),
                ('carbohydrates', models.FloatField(null=True)),
                ('sugars', models.FloatField(null=True)),
                ('fats', models.FloatField(null=True)),
                ('proteins', models.FloatField(null=True)),
                ('fibers', models.FloatField(null=True)),
                ('categories', models.ManyToManyField(to='snacks.Category')),
            ],
        ),
    ]
